### ISSUE TITLE
test_ship_receive.py

### ISSUE THREAD

**Issue by 19868** [muiyu/BookStore#2]
![image](https://github.com/user-attachments/assets/d62f0b87-914a-4ace-bdd9-71d49364bbf4)

**Comment by 19868** [comment]
加载数据到MongoDB后error消失，只剩搜索功能的报错信息了：
![image](https://github.com/user-attachments/assets/6b376624-a10e-48bf-8af3-b806b6501a11)

**Comment by muiyu** [comment]
If u dont know what ChatGPT is doing, please dont use its codes!!!!（哭
